platform :ios, "10.0"

target "RNTrackPlayer" do
  # React
  pod "FBLazyVector", :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod "FBReactNativeSpec", :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod "RCTRequired", :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod "RCTTypeSafety", :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod "React-Core", :path => "../node_modules/react-native/"
  pod "React-CoreModules", :path => "../node_modules/react-native/React/CoreModules"
  pod "React-RCTImage", :path => "../node_modules/react-native/Libraries/Image"
  pod "React-RCTNetwork", :path => "../node_modules/react-native/Libraries/Network"
  pod "React-Core/RCTWebSocket", :path => "../node_modules/react-native/"
  pod "React-cxxreact", :path => "../node_modules/react-native/ReactCommon/cxxreact"
  pod "React-jsi", :path => "../node_modules/react-native/ReactCommon/jsi"
  pod "React-jsiexecutor", :path => "../node_modules/react-native/ReactCommon/jsiexecutor"
  pod "React-jsinspector", :path => "../node_modules/react-native/ReactCommon/jsinspector"
  pod "ReactCommon/turbomodule/core", :path => "../node_modules/react-native/ReactCommon"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  
  # Swift Audio
  pod "SwiftAudio", "~> 0.11.0"
end
